import { SidebarGroupDoc } from "@/types/sidebar.types";

export const sidebarSeedData: SidebarGroupDoc[] = [
  {
    //  id: "catalog",
    title: "Catalog",
    order: 2,
    //  depth :2,
    roles: ["superAdmin", "admin"],
    type: "ordinary",
    items: [
      {
        //  id: "products",
        title: "Products",
        icon: "Package",
        roles: ["superAdmin", "admin"],
        order: 1,
        //  type: "non-leaf",
        children: [
          {
            //    id: "product-list",
            title: "All Products",
            icon: "List",
            url: "/admin/products",
            roles: ["superAdmin", "admin"],
            order: 1,
            //  type: "leaf",
          },
          {
            // id: "product-create",
            title: "Create Product",
            icon: "PlusCircle",
            url: "/admin/products/create",
            roles: ["superAdmin", "admin"],
            order: 2,
            // type: "leaf",
          },
        ],
      },
      {
        // id: "product-categories",
        title: "Categories",
        icon: "FolderTree",
        roles: ["superAdmin", "admin"],
        order: 2,
        //  submenuMode: "flyout",
        // type: "non-leaf",
        children: [
          {
            //   id: "category-list",
            title: "All Categories",
            icon: "List",
            url: "/admin/categories",
            roles: ["superAdmin", "admin"],
            order: 1,
            // type: "leaf",
          },
          {
            // id: "category-create",
            title: "Create Category",
            icon: "PlusCircle",
            url: "/admin/categories/create",
            roles: ["superAdmin", "admin"],
            order: 2,
            // type: "leaf",
          },
        ],
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    // id: "orders",
    title: "Invoices",
    order: 3,
    // depth :2,
    type: "ordinary",
    roles: ["superAdmin", "admin"],
    items: [
      {
        //   id: "orders-root",
        title: "Orders",
        order: 1,
        icon: "ShoppingCart",
        roles: ["superAdmin", "admin"],
        //  type: "non-leaf",
        children: [
          {
            //    id: "order-list",
            title: "All Orders",
            icon: "List",
            order: 1,
            url: "/admin/orders",
            roles: ["superAdmin", "admin"],
            //  type: "leaf",
          },
          {
            // id: "order-returns",
            title: "Returns",
            icon: "ArrowLeftRight",
            order: 2,
            url: "/admin/orders/returns",
            roles: ["superAdmin", "admin"],
            //type: "leaf",
          },
          {
            //id: "order-reports",
            title: "Order History",
            icon: "History",
            order: 3,
            url: "#",
            roles: ["superAdmin", "admin"],
            //type: "leaf",

            children: [
              {
                title: "Last 30 Days",
                url: "/admin/orders/reports",
                order: 1,
                roles: ["superAdmin", "admin"],
                children: [
                  {
                    title: "Level 3 Item",
                    url: "#",
                    order: 1,
                    roles: ["superAdmin", "admin"],
                  },
                  {
                    title: "Older",
                    url: "#",
                    order: 2,
                    roles: ["superAdmin", "admin"],
                    children: [
                      {
                        title: "Level 4 Item",
                        url: "#",
                        order: 1,
                        roles: ["superAdmin", "admin"],
                      },
                      {
                        title: "Older",
                        url: "#",
                        order: 2,
                        roles: ["superAdmin", "admin"],
                      },
                    ],
                  },
                ],
              },
              {
                title: "Older",
                order: 2,
                roles: ["superAdmin", "admin"],
                url: "#",
              },
            ],
          },
        ],
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    //   id: "inventory",
    title: "Inventory",
    order: 4,
    // depth :2,
    type: "ordinary",
    roles: ["superAdmin", "admin"],
    items: [
      {
        //id: "inventory-root",
        title: "stock",
        icon: "BarChart3",
        order: 1,
        roles: ["superAdmin", "admin"],
        //  type: "non-leaf",
        children: [
          {
            //  id: "stock-reports",
            title: "Stock Report",
            icon: "List",
            order: 1,
            url: "/admin/stock",
            roles: ["superAdmin", "admin"],
            //   type: "leaf",
          },
        ],
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
